# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-24 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('position', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'agents',
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'leagues',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('position', models.CharField(max_length=20)),
                ('student_id', models.IntegerField(blank=True, null=True)),
                ('is_approved', models.BooleanField()),
            ],
            options={
                'db_table': 'players',
            },
        ),
        migrations.CreateModel(
            name='Playground',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'playgrounds',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('sport', models.CharField(max_length=15)),
                ('site', models.CharField(max_length=40)),
                ('info', models.TextField()),
                ('age_type', models.CharField(max_length=15)),
                ('is_approved', models.BooleanField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nmfladminsite.Agent')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nmfladminsite.League')),
                ('playground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nmfladminsite.Playground')),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('sport', models.CharField(max_length=15)),
                ('age_type', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'tournaments',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nmfladminsite.Team'),
        ),
        migrations.AddField(
            model_name='league',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nmfladminsite.Tournament'),
        ),
    ]
